In [1]:
import numpy as np

In [2]:
np.maximum([2, 3, 4], [1, 5, 2])

array([2, 5, 4])

In [3]:
np.maximum(np.eye(2), [0.5, 2])

array([[1. , 2. ],
       [0.5, 2. ]])

In [4]:
np.maximum([np.nan, 0, np.nan], [0, np.nan, np.nan])

array([nan, nan, nan])

In [5]:
np.maximum(np.Inf, 1)

inf